version: '3.8'
services:
  backend:
    container_name: cfa-notification-services
    restart: always
    build: .
    ports:
      - '9000:9000'
    environment:
      - MONGO_USERNAME=hamlet
      - MONGO_PASSWORD=toor
